TAS.WebPortal/Controllers/SurveyController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TAS.Core.Entities.MasterData.Administrative;
using TAS.Core.Shared;
using TAS.Core.Shared.nCoV;
using TAS.WebPortal.Helper;
using TAS.WebPortal.Models;
using TAS.WebPortal.Provider;

namespace TAS.WebPortal.Controllers
{

    public class SurveyController : BaseController
    {
        private readonly string URL_MASTER = Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["HttpBaseAddress"]);
        private readonly string _Province = Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["DefaultProvince"]);
        private readonly int _pageSize = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["PAGESIZE"]);
        // GET: Survey
        private string _token;
        private string _token_id;
        private string _employeeId;
        public SurveyController()
        {
            if (User != null && !string.IsNullOrEmpty(User.Access_token))
            {
                _token = User.Access_token;
                _token_id = User.Token_ID;
                _employeeId = User.UserID;
            }
        }
        //[HttpGet]
        //public ActionResult Index()
        //{
        //    if (System.Web.HttpContext.Current.Session["expires"] != null)
        //    {
        //        #region Check session
        //        /*Kiểm tra token còn hạn ko?*/
        //        string _date = System.Web.HttpContext.Current.Session["expires"].ToString();
        //        if (!string.IsNullOrEmpty(_date))
        //        {
        //            DateTime date = Convert.ToDateTime(_date);
        //            if (date < DateTime.Now)
        //            {
        //                return RedirectToAction("Login", "Account");
        //            }
        //            else
        //            {
        //                var tmp = System.Web.HttpContext.Current.Session["unique_id"].ToString();
        //                _employeeId = PublicSecureProvider.Decrypt(tmp);
        //                //
        //                _token_id = System.Web.HttpContext.Current.Session["token_id"].ToString();
        //                _token = System.Web.HttpContext.Current.Session["access_token"].ToString();
        //                List<HR_Survey_Answer> lstAnswerFinish = Get_SurveyAnswer();
        //                return View (lstAnswerFinish);
        //            }
        //        }
        //        else
        //        {
        //            return RedirectToAction("Login", "Account");
        //        }
        //        #endregion
        //    }
        //    else return RedirectToAction("Login", "Account");
        //}

        [HttpGet]
        public ActionResult Index()
        {
            int size = _pageSize;
            List<HR_Survey_Answer> lstAnswerFinish = Get_SurveyAnswer();
            //lstAnswerFinish = taoList();
            if (lstAnswerFinish == null)
            {
                return View();
            }
            else
            {
                if (lstAnswerFinish.Count % size != 0)
                {
                    ViewBag.pageNumber = lstAnswerFinish.Count / size + 1;
                }
                else
                {
                    ViewBag.pageNumber = lstAnswerFinish.Count / size;
                }

                if (lstAnswerFinish.Count > _pageSize)
                {
                    //Chỉ lấy đủ size
                    List<HR_Survey_Answer> lstData = new List<HR_Survey_Answer>();
                    for (int i = 0; i < _pageSize; i++)
                    {
                        HR_Survey_Answer obj = new HR_Survey_Answer()
                        {
                            Survey_ID = lstAnswerFinish[i].Survey_ID,
                            EmployeeID = lstAnswerFinish[i].EmployeeID,
                            EffDate = lstAnswerFinish[i].EffDate,
                            EffDate_New = lstAnswerFinish[i].EffDate_New,
                            Token_ID = lstAnswerFinish[i].Token_ID
                        };

                        lstData.Add(obj);
                    }
                    return View(lstData);
                }
                else
                {
                    return View(lstAnswerFinish);
                }
            }

        }

        public string ViewPage(int index)
        {
            int n = _pageSize;
            List<HR_Survey_Answer> lstAnswerFinish = Get_SurveyAnswer();
            //lstAnswerFinish = taoList();
            string strData = string.Empty;
            strData += "<tr style='background:#228154'><th style='color:#fff'> NGÀY </th> <th style='color:#fff'>Chi tiết</th> </tr>";
            int i = n * index;
            int max = i + n;
            if (max > lstAnswerFinish.Count)
                max = lstAnswerFinish.Count;
            for (; i < max; i++)
            {
                strData += "<div class='row'><tr>";
                strData += string.Format("<td>{0}</td><td><a href='/khao-sat/Details/{1}'>Xem chi tiết</a></td>", lstAnswerFinish[i].EffDate_New, lstAnswerFinish[i].Survey_ID);
                strData += "</tr></div >";
            }
            return strData;
        }

        private List<HR_Survey_Answer> taoList()
        {
            List<HR_Survey_Answer> lstData = new List<HR_Survey_Answer>();
            int size = 55;
            for (int i = 0; i < size; i++)
            {
                HR_Survey_Answer obj = new HR_Survey_Answer()
                {
                    Survey_ID = i,
                    EmployeeID = i.ToString(),
                    EffDate = DateTime.Now.AddDays(-i),
                    EffDate_New = DateTime.Now.ToString("dd/MM/yyyy"),
                };
                lstData.Add(obj);
            }
            return lstData;
        }

        public ActionResult Create()
        {
            if (System.Web.HttpContext.Current.Session["expires"] != null)
            {
                #region Check session
                /*Kiểm tra token còn hạn ko?*/
                string _date = System.Web.HttpContext.Current.Session["expires"].ToString();
                if (!string.IsNullOrEmpty(_date))
                {
                    DateTime date = Convert.ToDateTime(_date);
                    if (date < DateTime.Now)
                    {
                        return RedirectToAction("Login", "Account");
                    }
                    else
                    {
                        var tmp = System.Web.HttpContext.Current.Session["unique_id"].ToString();
                        _employeeId = PublicSecureProvider.Decrypt(tmp);
                        //
                        _token_id = System.Web.HttpContext.Current.Session["token_id"].ToString();
                        _token = System.Web.HttpContext.Current.Session["access_token"].ToString();


                        ViewData["EFFDATE"] = string.Format("{0:dd/MM/yyyy}", DateTime.Now);
                        string strData1 = string.Empty;
                        string strData2 = string.Empty;
                        var objSurveyForm = Get_SurveyForm();
                        //
                        if (!string.IsNullOrEmpty(objSurveyForm.Employee.Namsinh))
                        {
                            ViewBag.NamSinh = genNamSinh(int.Parse(objSurveyForm.Employee.Namsinh));
                        }
                        else
                        {
                            ViewBag.NamSinh = genNamSinh(null);
                        }


                        ViewBag.Phai = genPhai(objSurveyForm.Employee.Phai);
                        ViewBag.QuocTich = genQuocTich(objSurveyForm.Employee.Quoctich.Trim());
                        ViewBag.KhoaPhong = Gen_Khoa(objSurveyForm.Employee.Makp);
                        ViewBag.Tinh = genTinh(objSurveyForm.Employee.Matt);
                        ViewBag.Quan = genQuan(objSurveyForm.Employee.Maqu, objSurveyForm.Employee.Matt);
                        ViewBag.Xa = genXa(objSurveyForm.Employee.Mapxa, objSurveyForm.Employee.Maqu);
                        int count = genCauHoi(objSurveyForm.Get_Question, ref strData1, ref strData2, objSurveyForm.IsFinished);
                        ViewBag.CauHoiChon = strData1;
                        ViewBag.CauHoi = strData2;
                        //
                        return View(objSurveyForm);

                    }
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
                #endregion
            }
            else return RedirectToAction("Login", "Account");
        }

        // POST: Employee/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Create(string objToKhai)
        {
            bool isUpdate = false;
            if (System.Web.HttpContext.Current.Session["expires"] != null)
            {
                #region Check session
                /*Kiểm tra token còn hạn ko?*/
                string _date = System.Web.HttpContext.Current.Session["expires"].ToString();
                if (!string.IsNullOrEmpty(_date))
                {
                    DateTime date = Convert.ToDateTime(_date);
                    if (date < DateTime.Now)
                    {
                        return Json(new { content = "Hết phiên đăng nhập", iserror = false }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var tmp = System.Web.HttpContext.Current.Session["unique_id"].ToString();
                        _employeeId = PublicSecureProvider.Decrypt(tmp);
                        //

TAS.WebPortal/Views/Shared/_InternalLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <!-- JQVMap -->
    @*<link href="~/Content/plugins/jqvmap/jqvmap.min.css"  rel="stylesheet" >
        <link href="~/Content/adminLTE/css/adminlte.min.css" rel="stylesheet" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">*@

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Content/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Content/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href='@Url.Action("Index","Home")' class="nav-link">Trang chủ</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href='@Url.Action("About","Home")' class="nav-link">Liên hệ</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                        <i class="fa fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href='@Url.Action("Index","Home")' class="brand-link">
                <img src="~/Content/images/logo.png" alt="QK7 Logo" class="brand-image img-circle elevation-3"                
                     style="opacity: .8">
                <span class="brand-text font-weight-light">QUÂN KHU 7</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/Content/bvquany7a/img/user64.png" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="@Url.Action("Index", "Manage")" class="d-block">@ViewBag.UserName</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href='@Url.Action("Index","Dashboard")' class="nav-link active">
                                <i class="nav-icon fa fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                    <i class="right fa fa-angle-left"></i>
                                </p>
                            </a>
                        </li>
                        @*<li class="nav-item">
                            <a href='@Url.Action("Index","Department")' class="nav-link">
                                <i class="nav-icon fa fa-th"></i>
                                <p>
                                    Báo cáo khoa
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>*@
                        <li class="nav-item">
                            <a href='@Url.Action("Index","Survey")' class="nav-link">
                                <i class="nav-icon fa fa-copy"></i>
                                <p>
                                    Sức khỏe cá nhân
                                    <i class="fa fa-angle-left right"></i>
                                    @*<span class="badge badge-info right">6</span>*@
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a  href="@Url.Action("ChangePassword", "Manage",routeValues:new {type=0,require=false })" class="nav-link">
                                <i class="nav-icon fa fa-chart-pie"></i>
                                <p>
                                    Đổi mật khẩu
                                    <i class="right fa fa-angle-left"></i>
                                </p>
                            </a>                            
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="min-height: 481px;">
            <div class="wrapper">
                <!-- Content Header (Page header) -->
                <div class="content-header">
                    <div class="container-fluid">
                        <div class="row mb-2">
                            <div class="col-sm-6">
                                <h1 class="m-0 text-dark">@ViewBag.Controller</h1>
                            </div><!-- /.col -->
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active">@ViewBag.Action</li>
                                </ol>
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                    </div><!-- /.container-fluid -->
                </div>
                <!-- /.content-header -->
                <!-- Main content -->
                <section class="content">
                    @RenderBody()
                </section>
                <!-- End Main content -->
            </div>
        </div>
    </div>

    <footer class="main-footer">
        <strong>Copyright &copy; 2021 by IT Dept</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 2.0.2
        </div>
    </footer>

    <!-- ./wrapper -->
    <!--Script-->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/plugins/jquery-ui/jquery-ui.min.js"></script>

    @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/adminLTE/adminlte.js"></script>
    <script src="~/Scripts/adminLTE/adminlte.min.js"></script>
    <script src="~/Scripts/adminLTE/demo.js"></script>
    <script src="~/Scripts/adminLTE/pages/dashboard.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>*@

    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Content/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/Content/plugins/jqvmap/jquery.vmap.js"></script>
    <script src="~/Content/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Content/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Content/plugins/moment/moment.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/Content/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>

</body>
</html>

TAS.WebPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Hệ thống thông tin quản lý khai báo y tế">
    <meta name="author" content="Hệ thống thông tin quản lý Khai báo Y tế">
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon">
    <meta name="description" content="">
    <meta name="keywords" content="tờ khai y tế, khai báo y tế, health declaration, khai y tế, bệnh viện 7A, 7AMH">
    <meta name="copyright" content="Hệ thống thông tin quản lý Khai báo Y tế - Quân khu 7">
    <title>Tờ khai y tế </title>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Oswald:300,400,500,600" rel="stylesheet" />
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content/bvquany7a/css/khaibao.css" rel="stylesheet" />
    <link href="~/Content/bvquany7a/css/login.css" rel="stylesheet" />
    <link href="~/Content/bvquany7a/css/main.css" rel="stylesheet" />
    <link href="~/Content/bvquany7a/css/plugin.css" rel="stylesheet" />
    <link href="~/Content/styledev.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body style="padding: 0px; margin: 0px; background-color: rgb(234, 234, 234);">
    <div id="toppage" class="page-wrap">
        <div class="header-info">
            <div class="container">
                <div class="tb-col">
                    <div class="col">
                        <div class="logo"><a href='@Url.Action("Index","Home", new { Areas=""})'><img src="@Url.Content("~/Content/bvquany7a/img/logo.png")" alt="logo" height="72" width="72" /></a></div>
                    </div>
                    @*<div class="col">
                            <address class="fa fa-map-marker">466 Nguyễn Trãi, P.8, Q.5, TPHCM</address>

                        </div>*@
                    <div class="col">
                        @{
                            Html.RenderPartial("_LoginPartial");
                        }
                    </div>
                </div>
            </div>

        </div>
        <div id="page-content">
            @RenderBody()
        </div>

    </div><!-- //page -->

    <footer class="footer-container">
        @*<div class="container info">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo"><a href="index.html"><img src="Content/bvquany7a/img/logo.png" alt="BV7A logo" /></a></div>
                        <p class="phone">Liên hệ<br /> <strong>028  3836 6789</strong></p>
                    </div>
                    <div class="col-sm-8">
                        <div class="row break-560">
                            <div class="col-xs-4 col">
                                <ul class="links">
                                    <li><a href="#">About our system</a></li>
                                    <li><a href="#">In the Community</a></li>
                                    <li><a href="#">Careers</a></li>
                                    <li><a href="#">IU Health Foundation</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-4 col">
                                <ul class="links">
                                    <li><a href="#">Patient & Family Support</a></li>
                                    <li><a href="#">Business Solutions</a></li>
                                    <li><a href="#">IU Health Plans</a></li>
                                    <li><a href="#">News Hub</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-4 col">
                                <ul class="links">
                                    <li><a href="#">For Researchers</a></li>
                                    <li><a href="#">For Providers</a></li>
                                    <li><a href="#">Professional Education</a></li>
                                    <li><a href="#">For Media </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr />*@
        <div class="container copyright">
            &copy; 2021 IT Dept. All rights reserved
        </div>
    </footer><!-- //footer container -->

    <a href="#toppage" class="smoothscroll gotop">Go top</a>  
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    @*<script type="text/javascript" language="javascript">
        function DisableBackButton() {
            window.history.forward()
        }
        DisableBackButton();
        window.onload = DisableBackButton;
        window.onpageshow = function (evt) { if (evt.persisted) DisableBackButton() }
        window.onunload = function () { void (0) }
    </script>*@
</body>
</html>

TAS.WebPortal/Views/Shared/_Navigation.cshtml
@using TAS.WebPortal.Models

<header class="header-container">
	<div id="menu" class="container menu-wrap">
		<ul class="menu">
			<li class="active"><a href='@Url.Action("Index","Home")'>Trang chủ</a></li>
			<li><a href='@Url.Action("About","Home")'>Giới thiệu</a></li>
			@if (Request.IsAuthenticated)
			{
				var authenUser = (CustomPrincipal)HttpContext.Current.User;
				if(authenUser.GroupID == 1 )//|| authenUser.GroupID == 2)
				{
					<li>
						<a href='@Url.Action("Index","Dashboard")'>Khoa phòng</a>
						<ul>
							<li><a href='@Url.Action("Index","Dashboard")'>Dashboard</a></li>
							<li><a href='@Url.Action("GetEmployees","Department")'>Danh sách nhân viên</a></li>
							@*<li><a href='@Url.Action("Index","Department")'>Báo cáo hằng ngày</a></li>*@
						</ul>
					</li>
				}	

			}
			<li><a href='@Url.Action("Index","Home")'>Kiến thức y khoa</a></li>
			<li><a href='@Url.Action("Index","Home")'>Tin tức</a></li>
			<li><a href='@Url.Action("Contact","Home")'>Liên hệ</a></li>
		</ul>
	</div>
</header>