TAS.WebPortal/Areas/Branch/Controllers/UsersController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TAS.Core.Entities.MasterData.Administrative;
using TAS.Core.Shared;
using TAS.Core.Shared.nCoV;
using TAS.WebPortal.Controllers;
using TAS.WebPortal.Helper;
using TAS.WebPortal.Models;
using TAS.WebPortal.Provider;

namespace TAS.WebPortal.Areas.Branch.Controllers
{
    public class UsersController : AdminBaseController
    {
        private readonly string URL_MASTER = Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["HttpBaseAddress"]);
        private readonly string _Province = Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["DefaultProvince"]);
        private readonly string _CustomerID = "46b26f68-18fd-11ea-9cef-33538cee559b";
        private readonly int _pageSize = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["PAGESIZE"]);
        // GET: Survey
        private string _token;
        private string _token_id;
        private string _employeeId;
        public UsersController() : base()
        {
            if (User != null && !string.IsNullOrEmpty(User.Access_token))
            {
                _token = User.Access_token;
                _token_id = User.Token_ID;
                _employeeId = User.UserID;
            }
            else RedirectToActionPermanent("Login", "Account");
        }
        // GET: Branch/Users
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        //[Route("Branch/Users")]
        //public ActionResult Index()
        //{
        //    ViewBag.BranchName = base._BranchName;
        //    return View();
        //}

        [Route("Index")]
        public ActionResult Index(int? page, string Keyword, string currentFilter)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["PAGESIZE"].ToString());

            ViewBag.BranchName = base._BranchName;
            if (Keyword != null)
                page = 1;
            else
                Keyword = currentFilter;
            ViewBag.CurrentFilter = Keyword;
            var obj = (from a in Get_ListEmployees().AsEnumerable()
                       select a);
            if (!string.IsNullOrEmpty(Keyword))
                obj = obj.Where(m => m.Dienthoai.ToUpper().Contains(Keyword.ToUpper()) ||
                m.Hoten.ToUpper().Contains(Keyword.ToUpper()));
            ViewBag.Model = obj;
            ViewBag.Makp = Gen_Khoa(base._BranchID, -1);
            int PageNumber = (page ?? 1);
            return View();
        }

        #region Get Danh Mục
        /// <summary>
        /// Danh sách nhân viên
        /// </summary>
        /// <returns></returns>
        private List<HR_Employees_Extend> Get_ListEmployees()
        {
            if (string.IsNullOrEmpty(_token))
            {
                return null;
            }

            #region Get data
            using (HttpClient client = new HttpClient())
            {
                List<HR_Employees_Extend> objReturn = new List<HR_Employees_Extend>();
                client.BaseAddress = new Uri(URL_MASTER);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _token);

                string api_name = string.Format("api/Survey/Get_ListEmployees?branch={0}", base._BranchID);
                Uri _Uri = new Uri(string.Format("{0}/{1}", URL_MASTER, api_name));
                HttpResponseMessage response;
                try
                {
                    response = client.GetAsync(_Uri).Result;
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = response.Content.ReadAsStringAsync().Result;
                        APIResult objTmp = JsonConvert.DeserializeObject<APIResult>(result);
                        if (objTmp.ResultCode == 0)
                        {
                            objReturn = JsonConvert.DeserializeObject<List<HR_Employees_Extend>>(objTmp.ResultData.ToString());
                        }
                        else
                        {
                            if (!string.IsNullOrEmpty(objTmp.Message))
                            {
                                objReturn = null;
                            }
                        }
                    }
                    else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                    {
                        objReturn = null;
                    }
                    else
                    {
                        objReturn = null;

                    }
                }
                catch
                {
                    objReturn = null;
                }

                return objReturn;
            }
            #endregion
        }

        /// <summary>
        /// Năm sinh
        /// </summary>
        /// <returns></returns>
        private string genNamSinh(int? namsinh)
        {

            int year = DateTime.Now.Year;
            int min = year - 70;
            int max = year - 18;

            string _html = string.Empty;
            for (int i = max; i >= min; i--)
            {

                if (namsinh.HasValue && namsinh.Value == i)
                {
                    _html += string.Format("<option value='{0}' selected>{1}</option>", i, i);
                }
                else
                {
                    _html += string.Format("<option value='{0}'>{1}</option>", i, i);
                }

            }
            return _html;
        }
        /// <summary>
        /// Giới tính
        /// </summary>
        /// <returns></returns>
        private string genPhai(int? phai)
        {
            string _html = string.Empty;

            if (phai.HasValue)
            {
                if (phai.Value == 1)
                {
                    _html = string.Format("<option value='{0}' >{1}</option>", 0, "Nam");
                    _html += string.Format("<option value='{0}' selected>{1}</option>", 1, "Nữ");
                }
                else
                {
                    _html = string.Format("<option value='{0}' selected>{1}</option>", 0, "Nam");
                    _html += string.Format("<option value='{0}'>{1}</option>", 1, "Nữ");
                }
            }
            else
            {
                _html = string.Format("<option value='{0}' selected>{1}</option>", 0, "Nam");
                _html += string.Format("<option value='{0}'>{1}</option>", 1, "Nữ");
            }

            return _html;
        }
        /// <summary>
        /// Quốc tịch
        /// </summary>
        /// <returns></returns>
        private string genQuocTich(string name)
        {
            string _html = string.Empty;
            if (!string.IsNullOrEmpty(name))
            {
                if (!name.Equals("VN"))
                {
                    _html = string.Format("<option value='{0}' >{1}</option>", "VN", "Việt Nam");
                    _html += string.Format("<option value='{0}' selected>{1}</option>", "khac", "Khác");
                }
                else
                {
                    _html = string.Format("<option value='{0}' selected>{1}</option>", "VN", "Việt Nam");
                    _html += string.Format("<option value='{0}'>{1}</option>", "khac", "Khác");
                }
            }
            else
            {
                _html = string.Format("<option value='{0}' selected>{1}</option>", "VN", "Việt Nam");
                _html += string.Format("<option value='{0}'>{1}</option>", "khac", "Khác");
            }


            return _html;

        }
        private string Gen_Khoa(int mapk = -1)
        {
            string _html = string.Empty;
            string _key = string.Format("dic_{0}", "department");
            List<HR_Department> lstDept = GetKhoaphong();
            if (lstDept != null && lstDept.Count > 0)
            {
                foreach (HR_Department obj in lstDept)
                {
                    if (obj.Ma == mapk)
                    {
                        _html += string.Format("<option value='{0}' selected>{1}</option>", obj.Ma, obj.Ten);
                    }
                    else
                    {
                        _html += string.Format("<option value='{0}'>{1}</option>", obj.Ma, obj.Ten);
                    }
                }
            }
            // _html = option_system.ToString();
            return _html;
        }
        /// <summary>
        /// Danh sách khoa phòng
        /// </summary>
        /// <returns></returns>
        private List<HR_Department> GetKhoaphong()
        {
            if (string.IsNullOrEmpty(_token))
            {
                return null;
            }

            #region Get data
            using (HttpClient client = new HttpClient())
            {
                List<HR_Department> objReturn = new List<HR_Department>();
                client.BaseAddress = new Uri(URL_MASTER);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _token);

                string api_name = string.Format("api/Survey/GetKhoaphong");
                Uri _Uri = new Uri(string.Format("{0}/{1}", URL_MASTER, api_name));
                HttpResponseMessage response;

TAS.WebPortal/Areas/Branch/Views/Users/AddUser.cshtml
@model TAS.WebPortal.Models.Employee
@using TAS.Core.Entities.MasterData.Administrative
@using TAS.Core.Shared.nCoV
@{
    ViewBag.Title = "AddUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/styledev.css" rel="stylesheet" />

@using (Html.BeginForm("AddUser", "Users", FormMethod.Post, new { id = "form", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="main">

            <div class="form-resign2">

                <!--thong tin hanh chính-->
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="form-group inline-block form-inline label-width ">
                            <h4 style="color:#228154; text-align:left">THÔNG TIN NGƯỜI DÙNG</h4>
                        </div>
                    </div>
                </div>
                <div class="row ">
                    <div class="form-group">
                        <label class="col-md-2">1.Họ và tên (IN HOA)<em>(*)</em></label>
                        <input class="col-md-4" id="txtName" name="txtName" type="text" maxlength="50" placeholder="Họ và tên (IN HOA)" />
                        <label class="col-md-2">2.Số CMND/CCCD </label>
                        <input class="col-md-4" id="txtCMND" name="txtCMND" type="text" maxlength="12" placeholder="Số CMND/CCCD" />
                    </div>
                    <div class="form-group">
                        <label class="col-md-2">Năm sinh<em>(*)</em> </label>
                        <select id="cboNamsinh" name="cboNamsinh" class="col-md-2">
                            @*<option>Chọn</option>*@
                            @Html.Raw(ViewBag.NamSinh)
                        </select>

                        <label class="col-md-2">Giới tính<em>(*)</em> </label>
                        <select id="cboGioTinh" name="cboGioTinh" class="col-md-2">
                            @*<option>Chọn</option>*@
                            @Html.Raw(ViewBag.Phai)
                        </select>

                        <label class="col-md-2">Quốc tịch<em>(*)</em> </label>
                        <select id="cboQuocTich" name="cboQuocTich" class="col-md-2">
                            @*<option>Chọn</option>*@
                            @Html.Raw(ViewBag.Quoctich)
                        </select>

                    </div>

                    <div class="form-group">
                        <label class="col-md-2">Số điện thoại<em>(*)</em></label>
                        <input class="col-md-4" id="txtSdt" name="txtSdt" type="number" maxlength="10" placeholder="Số điện thoại" />

                        <label class="col-md-2">Email: </label>
                        <input class="col-md-4" id="txtEmail" name="txtEmail" type="text" placeholder="Email" />
                    </div>

                    <div class="form-group">
                        <label class="col-md-2">Đơn vị <em>(*)</em></label>
                        <select id="cboKhoaPhong" name="cboKhoaPhong" class="col-md-2">
                            @*<option>Chọn</option>*@
                            @Html.Raw(ViewBag.KhoaPhong)
                        </select>

                        <label class="col-md-2">Nhóm người dùng<em>(*)</em> </label>
                        <select id="cboGroupID" name="cboGroupID" class="col-md-2">
                            <option value="3">Người dùng</option>
                            <option value="2">Quản lý đơn vị</option>
                            <option value="1">Quản trị hệ thống</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="col-md-12">Địa chỉ chỗ ở hiện nay:</label>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2">Tỉnh/TP<em>(*)</em> </label>
                        <select id="cboTinh" name="cboTinh" class="col-md-2" onchange="cboTinh_Change()">
                            @Html.Raw(ViewBag.Tinh)
                        </select>

                        <label class="col-md-2">Quận/Huyện<em>(*)</em> </label>
                        <select id="cboQuan" name="cboQuan" class="col-md-2" onchange="cboQuan_Change()">
                            <option>Chọn</option>
                            @Html.Raw(ViewBag.Quan)
                        </select>

                        <label class=" col-md-2">Phường/Xã<em>(*)</em> </label>
                        <select id="cboXa" name="cboXa" class="col-md-2">
                            <option>Chọn</option>
                            @Html.Raw(ViewBag.Xa)
                        </select>
                    </div>

                    <div class="form-group">
                        <label class=" col-md-12">Địa chỉ nơi ở tại Việt Nam (Số nhà, phố, tổ dân phố/thôn/đội, phường/xã, quận, huyện, tỉnh/thành phố)<em>(*)</em></label>
                    </div>
                    <div class="form-group">
                        <input id="txtDiaChi" name="txtDiaChi" class="col-md-12" type="text" placeholder="Chỗ ở hiện nay" maxlength="50" />
                    </div>


                    <div class="row">
                        <div class="col-md-12 col-xs-12">
                            <div class="form-group inline-block form-inline label-width ">
                                <center>
                                    @*<input type="button" value="LƯU THÔNG TIN" onclick="location.href='@Url.Action("", "")'" />*@
                                    <input type="submit" value="LƯU THÔNG TIN" />
                                    <input type="button" value="QUAY LẠI" onclick="location.href='@Url.Action("Index", "Users")'" />
                                </center>
                            </div>

                            @*<div class="form-group inline-block form-inline label-width ">
                                    @Html.ActionLink("Back to List", "Index")
                                </div>*@
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>

    <div class="modal fade" id="modalNoti" tabindex="-1" data-backdrop="static">
        <div class="modal-dialog" role="document" style="">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Thông báo</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <span id="txtNoti">Thêm người dùng không thành công!</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="login-btn">
                        <button class="btn btn-default" data-dismiss="modal" aria-label="Close" id="btnCloseArlet"><i class="fa icon-close"></i> <span style="margin-left:3%">Đóng</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalSuccess" tabindex="-1" data-backdrop="static">
        <div class="modal-dialog" role="document" style="">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Thông báo</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <span id="txtSuccess"> Thêm người dùng thành công! </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="login-btn">
                        <a class="btn btn-primary" id="btnCloseArlet" href="/Branch/Users/Index">Đóng</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
<script type="text/javascript" async="" src="https://www.gstatic.com/recaptcha/releases/qpy2aGtSgsYPZzCoYWjcaBCo/recaptcha__en.js"></script>
<script src="~/Scripts/tokhai.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Areas/Branch/JS/user.js"></script>

TAS.WebPortal/Areas/Branch/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>

    table, th, td {
        border: 1px solid gray;
        border-collapse: collapse;
        white-space: nowrap;
    }

    th {
        padding: 4px;
        text-align: center;
        background-color: #228154;
        color: white;
    }

    td {
        padding: 4px;
    }
</style>

@using (Html.BeginForm("Index", "Users", FormMethod.Post, new { id = "form", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="main">

            <div class="form-resign2">

                <!--thong tin hanh chính-->
                <div class="row">
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        @*<div><h1>@ViewBag.BranchName</h1></div>*@
                        <ol class="breadcrumb">
                            <li><a href="@Url.Action("AddUser","Users")" class="btn btn-sm btn-info" style="color:#ffffff">Thêm mới </a></li>

                        </ol>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <div class="form-group inline-block form-inline label-width ">
                            <h4 style="color:#228154; text-align:left">QUẢN LÝ NGƯỜI DÙNG THUỘC @ViewBag.BranchName</h4>
                        </div>
                    </div>
                </div>

                <div class="row" style="margin: 10px">
                    <!--Tìm kiếm thông tin-->
                    <label class="col-md-1">Đơn vị:</label>
                    <select class="form-control col-md-3" id="cboMakp">
                        @Html.Raw(ViewBag.Makp)
                    </select>

                    <label class="col-md-1">Từ khóa:</label>
                    <input class="form-control col-md-3" type="text" id="key" placeholder="tên nhân viên" style="margin-right:5px"/>

                    <a id="btnSearch" class="form-control col-md-2 btn btn-info" >Tìm kiếm</a>
                </div>

                <div class="row ">
                    <div class="table-responsive">
                        <table id="DataTable" class="table align-items-center table-flush">
                            <thead>
                                @*class="thead-light"*@
                                <tr>
                                    <th style="color:#ffffff">Số điện thoại</th>
                                    <th style="color:#ffffff">Họ tên</th>
                                    <th style="color:#ffffff">Năm sinh</th>
                                    <th style="color:#ffffff">Số nhà</th>
                                    <th style="color:#ffffff">Khoa ban</th>
                                    <th style="color:#ffffff">Kích hoạt</th>
                                    <th style="color:#ffffff"></th>
                                    <th style="color:#ffffff"><button type="submit" class="btn btn-sm btn-danger" name="btnxoa" id="btnxoa" onclick="ConfirmReset()">Xóa</button></th>
                                </tr>
                            </thead>
                            <tbody id="dtTable">
                                @{int i = 1;}
                                @foreach (var item in ViewBag.Model)
                                {
                                    <tr>
                                        <td>@item.Dienthoai</td>
                                        <td style="text-transform: uppercase">@item.Hoten</td>
                                        <td style="text-align:center">@item.Namsinh</td>
                                        <td>@item.Sonha</td>
                                        <td>@item.Tenkp</td>
                                        <td style="text-align:center">
                                            @if (item.Isactive == 1)
                                            {
                                                <input type="checkbox" id="isactive" name="isactive" checked value="@item.Isactive" />
                                            }
                                            else
                                            {
                                                <input type="checkbox" id="isactive" name="isactive" value="@item.Isactive" />
                                            }
                                        </td>

                                        <td align="center">
                                            <a class="btn btn-sm btn-info btn-update">Sửa</a>
                                            <a class="btn btn-sm btn-info btn-confirm" style="color:yellow" onclick="ConfirmReset()"> Reset mật khẩu</a>
                                        </td>
                                        <td align="center">
                                            <input name="ChkAr" id="ChkAr" value="" type="checkbox" class="custom-control custom-checkbox" />
                                        </td>
                                    </tr>
                                    i++;
                                }

                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
}

<div class="modal fade" id="modalNoti" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog" role="document" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <span id="txtNoti">Xác nhận cấp lại mật khẩu?</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="login-btn">
                    <button class="btn btn-default" data-dismiss="modal"><i class="fa ui-icon-info"></i> <span style="margin-left:3%">OK</span></button>

                    <button class="btn btn-default" data-dismiss="modal" aria-label="Close" id="btnCloseArlet"><i class="fa icon-close"></i> <span style="margin-left:3%">Đóng</span></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
            $("#DataTable").on('click', '.btn-confirm', function () {
                var x = confirm("Xác nhận cấp lại mật khẩu?");
                if (x) {
                    var currentRow = $(this).closest("tr");
                    var col2 = currentRow.find("td:eq(0)").text();
                    var data = col2;
                    alert(data)
                    var statesProgress = $("#states-loading-progress");
                        statesProgress.show();
                        $.ajax({
                            cache: false,
                            type: "POST",
                            //url: '@Url.Action("ResetPass")',
                            url: "Users/ResetPass/"+ data,
                            data: { "id": data},
                            success: function (data) {
                                if (data != null) {
                                    var vdata = data;
                                }
                                statesProgress.hide();
                            }
                        });
                    return true;
                }
                else
                    return false;
            });
        });

    $(document).ready(function () {
        $("#DataTable").on('click', '.btn-update', function () {
            debugger;
            var currentRow = $(this).closest("tr");
            var col2 = currentRow.find("td:eq(0)").text();
            var data = col2;

            window.open("Users/UpdateUser/" + data);

            });
        });

    document.getElementById("btnSearch").onclick = function () { FindUser() };

    function FindUser() {
        debugger;
        var params = {
            makp: $('#cboMakp').val(),
            key: $('#key').val(),
        };

        $.ajax({
            url: '/Branch/Users/FindUser',
            type: 'POST',
            data: params,
            dataType: "json",
            success: function (data) {
                if (!data.iserror) {
                    $('#dtTable').html(data.content);
                }
                else {
                    alert('Đã có lỗi xảy ra, vui lòng thử lại sau!');
                }
            },
        });
    }

</script>

TAS.WebPortal/Areas/Branch/Views/Users/partialNoti.cshtml
<div class="modal fade" id="modalNoti" data-backdrop="static">
    <div class="modal-dialog" role="document" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <span id="txtNoti">@ViewBag.strNoti </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="login-btn">
                    <button class="btn btn-default" data-dismiss="modal" aria-label="Close" id="btnCloseArlet">
                        <i class="fa icon-close"></i> <span style="margin-left:3%">Đóng</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

TAS.WebPortal/Areas/Branch/Views/Users/partialSuccess.cshtml
<div class="modal fade" id="modalSuccess" data-backdrop="static">
    <div class="modal-dialog" role="document" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <span > Thêm mới người dùng thành công</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="login-btn">
                    <a class="btn btn-primary" id="btnCloseArlet" href="/Branch/Users/Index">Đóng</a>
                </div>
            </div>
        </div>
    </div>
</div>