TAS.WebPortal/Controllers/DepartmentController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TAS.Core.Shared;
using TAS.Core.Shared.nCoV;
using TAS.WebPortal.Helper;
using TAS.WebPortal.Provider;

namespace TAS.WebPortal.Controllers
{
    public class DepartmentController : BaseController
    {
        private readonly string URL_MASTER = Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["HttpBaseAddress"]);
      //  private readonly string _Province = Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["DefaultProvince"]);
        // GET: Survey
        private string _token;
        private string _token_id;
        private string _employeeId;
        /// <summary>
        /// Thông tin nhân viên của user dang nhap
        /// </summary>
        private HR_Employees_Extend employeeInfo;
        public DepartmentController()
        {

        }
        // GET: Department
        //   [Authorize(Roles = "Moderate")]
        [HttpGet]
        public ActionResult Index()
        {
            List<HR_Dept_Report> lst = new List<HR_Dept_Report>();
            _token = System.Web.HttpContext.Current.Session["access_token"].ToString();

            lst = new nCOV(_token,null).GetList_HR_Dept_Report();

            return View(lst);
        }

       
        // GET: Department/Details/5
        //  [Authorize(Roles = "Moderate")]
        public ActionResult Details(int id)
        {
            TAS.Core.Shared.nCoV.HR_Dept_Report obj = new Core.Shared.nCoV.HR_Dept_Report();
            return View(obj);
        }

        // GET: Department/Create
    //    [Authorize(Roles = "Moderate")]
        public ActionResult Create()
        {
            //groupid == 2 mới được vào form
            if (System.Web.HttpContext.Current.Session["expires"] != null)
            {
                #region Check session
                /*Kiểm tra token còn hạn ko?*/
                string _date = System.Web.HttpContext.Current.Session["expires"].ToString();
                if (!string.IsNullOrEmpty(_date))
                {
                    DateTime date = Convert.ToDateTime(_date);
                    if (date < DateTime.Now)
                    {
                        return RedirectToAction("Login", "Account");
                    }
                    else
                    {
                        var tmp = System.Web.HttpContext.Current.Session["unique_id"].ToString();
                        _employeeId = PublicSecureProvider.Decrypt(tmp);
                        //
                        _token_id = System.Web.HttpContext.Current.Session["token_id"].ToString();
                        _token = System.Web.HttpContext.Current.Session["access_token"].ToString();
                        employeeInfo = GetHR_Employees(_employeeId);
                        if (employeeInfo != null)
                        {
                            List<HR_Employees_Extend> empList = Get_EmployeesFull_By_Makp(employeeInfo.Makp);
                            ViewData["TENKP"] = employeeInfo.Tenkp.ToUpper();
                            HR_Dept_Report obj = new HR_Dept_Report()
                            {
                                Makp=employeeInfo.Makp,
                                Tenkp=employeeInfo.Tenkp,
                                Nguoibc=employeeInfo.Hoten
                            };
                            return View(obj);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home");
                        }

                    }
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
                #endregion
            }
            else return RedirectToAction("Login", "Account");
            
        }

        // POST: Department/Create
     //   [Authorize(Roles = "Moderate")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                HR_Dept_Report obj = new HR_Dept_Report();

                if (!string.IsNullOrEmpty(collection["txtNgayBC"]))
                {
                    DateTime dtNgaybc = Convert.ToDateTime(collection["txtNgayBC"]);

                    obj.Ngaybc = dtNgaybc.ToString("dd/MM/yyyy");
                }

                if (!string.IsNullOrEmpty(collection["txtMakp"])) obj.Makp = Convert.ToInt32(collection["txtMakp"]);
                if (!string.IsNullOrEmpty(collection["txtTenkp"])) obj.Tenkp = Convert.ToString(collection["txtTenkp"]);
                //if (!string.IsNullOrEmpty(collection["txtNgayBC"])) obj.Ngaybc = Convert.ToString(collection["txtNgayBC"]);
                if (!string.IsNullOrEmpty(collection["txtQuanSo"])) obj.Quanso = Convert.ToInt32(collection["txtQuanSo"]);
                if (!string.IsNullOrEmpty(collection["txtHienCo"])) obj.Hienco = Convert.ToInt32(collection["txtHienCo"]);
                if (!string.IsNullOrEmpty(collection["txtHocViec"])) obj.Vang = Convert.ToInt32(collection["txtHocViec"]);
                if (!string.IsNullOrEmpty(collection["txtVang"])) obj.Hocviec = Convert.ToInt32(collection["txtVang"]);
                if (!string.IsNullOrEmpty(collection["txtLydoVang"])) obj.Lydovang = Convert.ToString(collection["txtLydoVang"]);
                if (!string.IsNullOrEmpty(collection["txtKhaibao"])) obj.Khaibao = Convert.ToInt32(collection["txtKhaibao"]);
                if (!string.IsNullOrEmpty(collection["txtBoSung"])) obj.Bosung = Convert.ToInt32(collection["txtBoSung"]);
                
                if (!string.IsNullOrEmpty(collection["txtKhac"])) obj.Khac = Convert.ToString(collection["txtKhac"]);
                if (!string.IsNullOrEmpty(collection["txtDeXuat"])) obj.Dexuat = Convert.ToString(collection["txtDeXuat"]);

                if (!string.IsNullOrEmpty(collection["txtNguoiBaoCao"])) obj.Nguoibc = Convert.ToString(collection["txtNguoiBaoCao"]);
                if (!string.IsNullOrEmpty(collection[""])) obj.Trangthai = 0;
                //if (!string.IsNullOrEmpty(collection[""])) obj.CreatedUser = Convert.ToInt32(collection[""]);

                _token = System.Web.HttpContext.Current.Session["access_token"].ToString();

                var bol = new nCOV(_token,null).Add_HR_Dept_Report(obj);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Edit/5
        [HttpGet]
      //  [Authorize(Roles = "Moderate")]
        public ActionResult Edit(int id)
        {
            //groupid == 2 mới được vào form

            TAS.Core.Shared.nCoV.HR_Dept_Report obj = new Core.Shared.nCoV.HR_Dept_Report()
            {
                Id = 1,
                Makp = 1,
                Tenkp = "Phòng khám nội tổng quát",
                Stt = 1,
                Quanso = 100,
                Hienco = 95,
                Vang = 5,
                Hocviec = 10,
                Lydovang = "Không thích học nữa nghỉ >_<",
                Trangthai = 0
            };
            return View(obj);
        }

        // POST: Department/Edit/5
        [HttpPost]
      //  [Authorize(Roles = "Moderate")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Delete/5
        public ActionResult Delete(int id)
        {
            TAS.Core.Shared.nCoV.HR_Dept_Report obj = new Core.Shared.nCoV.HR_Dept_Report()
            {
                Id = 1,
                Makp = 1,
                Tenkp = "Phòng khám nội tổng quát",
                Stt = 1,
                Quanso = 100,
                Hienco = 95,
                Vang = 5,
                Hocviec = 10,
                Lydovang = "Không thích học nữa nghỉ >_<",
                Trangthai = 0
            };
            return View(obj);
        }

        // POST: Department/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult GetEmployees()
        {
            if (System.Web.HttpContext.Current.Session["expires"] != null)
            {
                #region Check session
                /*Kiểm tra token còn hạn ko?*/
                string _date = System.Web.HttpContext.Current.Session["expires"].ToString();
                if (!string.IsNullOrEmpty(_date))
                {
                    DateTime date = Convert.ToDateTime(_date);
                    if (date < DateTime.Now)
                    {
                        return RedirectToAction("Login", "Account");
                    }
                    else
                    {
                        var tmp = System.Web.HttpContext.Current.Session["unique_id"].ToString();
                        _employeeId = PublicSecureProvider.Decrypt(tmp);
                        //
                        _token_id = System.Web.HttpContext.Current.Session["token_id"].ToString();
                        _token = System.Web.HttpContext.Current.Session["access_token"].ToString();
                        employeeInfo = GetHR_Employees(_employeeId);
                        if (employeeInfo != null)
                        {

TAS.WebPortal/Views/Department/Create.cshtml
@model TAS.Core.Shared.nCoV.HR_Dept_Report
@using TAS.WebPortal.Models
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Request.IsAuthenticated)
{
    var authenUser = (CustomPrincipal)HttpContext.Current.User;
    if (authenUser.GroupID == 1 || authenUser.GroupID == 2)
    {
    <div class="banner">
        @{
            Html.RenderPartial("_Navigation");
        }
    </div>
    }
}
<div class="container">
    <div class="main">
        <div class="container">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h3>BÁO CÁO @ViewData["TENKP"].ToString().ToUpper() NGÀY @DateTime.Now.ToString("dd/MM/yyyy")</h3>
                <div class="form-resign2">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="form-group">
                            <input id="txtMakp" name="txtMakp" value="@Model.Makp" hidden />

                            <label class="col-md-1">Tên khoa:<em>(*)</em> </label>
                            <input class="col-md-11" name="txtTenkp" id="txtTenkp" type="text" maxlength="12" placeholder="Tên khoa" value="@Model.Tenkp" readonly style="cursor:not-allowed" />
                            @Html.ValidationMessageFor(model => model.Tenkp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-1">Ngày:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtNgayBC" id="txtNgayBC" type="date" value="@Model.Ngaybc_yyyymmdd" />
                            @Html.ValidationMessageFor(model => model.Ngaybc, "", new { @class = "text-danger" })

                            @*<label class="col-md-1">STT:<em>(*)</em> </label>
                                <input class="col-md-2" id="txtStt" type="number" value="@Model.Stt" min="0" />
                                @Html.ValidationMessageFor(model => model.Stt, "", new { @class = "text-danger" })*@

                            <label class="col-md-1">Quân số:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtQuanSo" id="txtQuanSo" type="number" value="@Model.Quanso" min="0" />
                            @Html.ValidationMessageFor(model => model.Quanso, "", new { @class = "text-danger" })

                            <label class="col-md-1">Hiện có:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtHienCo" id="txtHienCo" type="number" value="@Model.Hienco" min="0" />
                            @Html.ValidationMessageFor(model => model.Hienco, "", new { @class = "text-danger" })

                            <label class="col-md-1">Học việc:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtHocViec" id="txtHocViec" type="number" value="@Model.Hocviec" min="0" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-1">Vắng:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtVang" id="txtVang" type="number" value="@Model.Vang" min="0" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                            <label class="col-md-1">Lý do:<em>(*)</em> </label>
                            <input class="col-md-4" name="txtLydoVang" id="txtLydoVang" type="text" maxlength="12" placeholder="Lý do vắng" value="@Model.Lydovang" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                            <label class="col-md-2">Người báo cáo:<em>(*)</em> </label>
                            @*<input class="col-md-2" name="txtNguoiBaoCao" id="txtNguoiBaoCao" type="text" value="@Model.Nguoibc" readonly style="cursor:not-allowed" />*@
                            <input class="col-md-2" name="txtNguoiBaoCao" id="txtNguoiBaoCao" type="text" value="0344511846" readonly style="cursor:not-allowed" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-1">Khai báo:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtKhaibao" id="txtKhaibao" type="number" value="@Model.Khaibao" min="0" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                            <label class="col-md-1">Bổ sung:<em>(*)</em> </label>
                            <input class="col-md-2" name="txtBoSung" id="txtBoSung" type="number" value="@Model.Bosung" min="0" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                            <label class="col-md-1">Lý do:<em>(*)</em> </label>
                            <input class="col-md-5" name="txtLydoVang" id="txtLydoVang" type="text" maxlength="12" placeholder="Lý do khai báo bổ sung" value="@Model.Lydo" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-12">Khác:<em>(*)</em> </label>
                            <input class="col-md-12" name="txtKhac" id="txtKhac" type="text" placeholder="Tình hình khác" value="@Model.Khac" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-12">Đề xuất:<em>(*)</em> </label>
                            <input class="col-md-12" name="txtDeXuat" id="txtDeXuat" type="text" placeholder="Đề xuất" value="@Model.Dexuat" />
                            @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <center>
                            <input type="submit" value="GỬI PHIẾU" class="btn btn-default" />
                            <input type="button" value="QUAY LẠI" onclick="location.href='@Url.Action("Index", "Department")'" />
                        </center>
                    </div>
                </div>

                <!-- @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                 <div class="form-group">
                     @Html.LabelFor(model => model.Makp, htmlAttributes: new { @class = "control-label col-md-2" })
                     <div class="col-md-10">
                         @Html.EditorFor(model => model.Makp, new { htmlAttributes = new { @class = "form-control" } })
                         @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                     </div>
                 </div>
                -->
            }

        </div>
    </div>

</div>

TAS.WebPortal/Views/Department/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="banner">
    @{
        Html.RenderPartial("_Navigation");
    }    
</div>
<div class="container">
    <div class="main">
        <h2>TỔNG HỢP THÔNG TIN</h2>
    </div>
    
</div>

TAS.WebPortal/Views/Department/Delete.cshtml
@model TAS.Core.Shared.nCoV.HR_Dept_Report

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HR_Dept_Report</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Makp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Makp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tenkp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenkp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngaybc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaybc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quanso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quanso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hienco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hienco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lydovang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lydovang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hocviec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hocviec)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Khaibao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khaibao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bosung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bosung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lydo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lydo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Khac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dexuat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dexuat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nguoibc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nguoibc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nguoigui)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nguoigui)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngaygui)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaygui)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TAS.WebPortal/Views/Department/Edit.cshtml
@model TAS.Core.Shared.nCoV.HR_Dept_Report

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="main">
        <div class="container">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-resign2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-1">Mã khoa:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtMakp" type="text" value="@Model.Makp" readonly style="cursor:not-allowed" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                        <label class="col-md-1">Tên khoa:<em>(*)</em> </label>
                        <input class="col-md-8" id="txtTenkp" type="text" maxlength="12" placeholder="Tên khoa" value="@Model.Tenkp" />
                        @Html.ValidationMessageFor(model => model.Tenkp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-1">Ngày:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtNgayBC" type="date" value="@Model.Ngaybc_yyyymmdd" />
                        @Html.ValidationMessageFor(model => model.Ngaybc, "", new { @class = "text-danger" })

                        @*<label class="col-md-1">STT:<em>(*)</em> </label>
                <input class="col-md-2" id="txtStt" type="number" value="@Model.Stt" min="0" />
                @Html.ValidationMessageFor(model => model.Stt, "", new { @class = "text-danger" })*@

                        <label class="col-md-1">Quân số:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtQuanSo" type="number" value="@Model.Quanso" min="0" />
                        @Html.ValidationMessageFor(model => model.Quanso, "", new { @class = "text-danger" })

                        <label class="col-md-1">Hiện có:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtHienCo" type="number" value="@Model.Hienco" min="0" />
                        @Html.ValidationMessageFor(model => model.Hienco, "", new { @class = "text-danger" })

                        <label class="col-md-1">Học việc:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtHocViec" type="number" value="@Model.Hocviec" min="0" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-1">Vắng:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtVang" type="number" value="@Model.Vang" min="0" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                        <label class="col-md-1">Lý do:<em>(*)</em> </label>
                        <input class="col-md-4" id="txtLydoVang" type="text" maxlength="12" placeholder="Lý do vắng" value="@Model.Lydovang" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                        <label class="col-md-2">Người báo cáo:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtNguoiBaoCao" type="text" value="@Model.Ngaybc" readonly style="cursor:not-allowed" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-1">Khai báo:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtKhaibao" type="number" value="@Model.Khaibao" min="0" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                        <label class="col-md-1">Bổ sung:<em>(*)</em> </label>
                        <input class="col-md-2" id="txtBoSung" type="number" value="@Model.Bosung" min="0" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })

                        <label class="col-md-1">Lý do:<em>(*)</em> </label>
                        <input class="col-md-5" id="txtLydoVang" type="text" maxlength="12" placeholder="Lý do khai báo bổ sung" value="@Model.Lydo" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-12">Khác:<em>(*)</em> </label>
                        <input class="col-md-12" id="txtKhac" type="text" placeholder="Tình hình khác" value="@Model.Khac" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-12">Đề xuất:<em>(*)</em> </label>
                        <input class="col-md-12" id="txtDeXuat" type="text" placeholder="Đề xuất" value="@Model.Dexuat" />
                        @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <center>
                        @Html.ActionLink("Back to List", "Index")

                        <input type="submit" value="Cập nhật phiếu" class="btn btn-default" />
                    </center>
                </div>
            </div>

                <!-- @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                 <div class="form-group">
                     @Html.LabelFor(model => model.Makp, htmlAttributes: new { @class = "control-label col-md-2" })
                     <div class="col-md-10">
                         @Html.EditorFor(model => model.Makp, new { htmlAttributes = new { @class = "form-control" } })
                         @Html.ValidationMessageFor(model => model.Makp, "", new { @class = "text-danger" })
                     </div>
                 </div>
                -->
            }

            @*<div>
                @Html.ActionLink("Back to List", "Index")
            </div>*@
        </div>
    </div>

</div>

TAS.WebPortal/Views/Department/GetEmployees.cshtml
@using TAS.Core.Shared.nCoV
@model IEnumerable<HR_Employees_Extend>
@{
    ViewBag.Title = "GetEmployees";
    //Layout = "~/Views/Shared/_Layout.cshtml
     Layout = "~/Views/Shared/_InternalLayout.cshtml";
}
<style>
    table tbody tr th {
        color: white;
    }
</style>

<div class="container">
    <div class="main">
        <div class="container">
            <div class="row">
                <div class="form-group">
                    <h4 class="col-md-2" style="min-width:25%;">DANH SÁCH NHÂN VIÊN</h4>
                    <select id="cboMakp" class="col-md-2" style="min-width:25%" onchange="cboMakp_Change()">
                        <option>Chọn</option>
                        @Html.Raw(ViewBag.Makp)
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                </div>
            </div>
        </div>
        <div class="container" id="Emplist">
            @{
                Html.RenderPartial("_EmployeeListPartial", Model);
            }
        </div>

    </div>
</div>

<script>
        function cboMakp_Change() {
        var idMakp = $('#cboMakp').val();
        var obj = "<option value='-2'>Chọn</option>";
        if (idMakp == '-2') {
           alert('Chọn khoa phòng cần xem!');
            return;
        }
        var empDiv = $("#Emplist");
        $.ajax({
            type: 'POST',
            url: '/Department/genEmployees',
            data: {
                makp: idMakp,
            }

        }).done(function (data) {
            $('#tbdata').html(data);

            @*if (data != null) {
                $("#Emplist").load('@(Url.Action("GetEmployeesByDept","Department",null, Request.Url.Scheme))?makp=' + iMakp);

            }
            else {

               alert('Không tìm thấy thông tin!');
            }*@
        });
    }
</script>
@*<script type="text/javascript">

        $(document).ready(function () {
            $("#cboMakp").change(function () {
                var iMakp =  $("#cboMakp").val();
                   $("#Emplist").load('@(Url.Action("GetEmployeesByDept","Department",null, Request.Url.Scheme))?makp=' + iMakp);
            });
        });
    </script>*@